[[redirects]]
  from = "https://modest-golick-0606ee.netlify.com/*"
  to = "https://www.vocast.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://piges.vocast.fr/*"
  to = "https://piges.voca.st"
  status = 200
  force = true

[[redirects]]
  from = "https://zaps.vocast.fr/*"
  to = "https://zaps.voca.st"
  status = 200
  force = true

[[redirects]]
  from = "https://blog.vocast.fr/*"
  to = "https://blog.voca.st"
  status = 200
  force = true

[[redirects]]
  from = "https://premium.vocast.fr/*"
  to = "https://premium.voca.st"
  status = 200
  force = true


[[redirects]]
  from = "https://sondage.vocast.fr/*"
  to = "https://www.vocast.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://desondes.vocast.fr/*"
  to = "https://www.vocast.fr/desondes/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.vocast.fr/vocazap/zaps"
  to = "https://zaps.voca.st"
  status = 200
  force = true

[[redirects]]
  from = "https://www.vocast.fr/vocazap/zap"
  to = "https://zaps.voca.st"
  status = 200
  force = true

[[redirects]]
  from = "https://www.vocast.fr/vocazap/records"
  to = "https://piges.voca.st"
  status = 200
  force = true

[[redirects]]
  from = "https://www.vocast.fr/vocazap/record"
  to = "https://piges.voca.st"
  status = 200
  force = true

[[redirects]]
  from = "/pep-sw.js"
  to = "https://pep.dev/pep-sw.js"
  status = 200
  force = true

[[redirects]]
  from = "/desondes/main/*"
  to = "https://d2qx8kkaq3fdmc.cloudfront.net/desondes/main-feed/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/desondes/full-only/*"
  to = "https://d2qx8kkaq3fdmc.cloudfront.net/desondes/full-only-feed/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/desondes/extracts-only/*"
  to = "https://d2qx8kkaq3fdmc.cloudfront.net/desondes/extracts-only-feed/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/desondes/rss/main"
  to = "https://www.spreaker.com/show/2886866/episodes/feed"
  status = 200
  force = true

[[redirects]]
  from = "/desondes/rss/full-only"
  to = "https://feed.ausha.co/yORLSkl8k09o"
  status = 200
  force = true

[[redirects]]
  from = "/desondes/rss/extracts-only"
  to = "https://www.spreaker.com/show/3033352/episodes/feed"
  status = 200
  force = true

[[redirects]]
  from = "https://earlocal.vocast.fr"
  to = "https://datastudio.google.com/reporting/5f56926f-7b8b-40da-be7c-c74c69e2ccb3"
  status = 301
  force = true 